ren SuperPro.b#1 SuperPro1.brd
ren SuperPro.b#2 SuperPro2.brd
ren SuperPro.b#3 SuperPro3.brd
ren SuperPro.b#4 SuperPro4.brd
ren SuperPro.b#5 SuperPro5.brd
ren SuperPro.b#6 SuperPro6.brd
ren SuperPro.b#7 SuperPro7.brd
ren SuperPro.b#8 SuperPro8.brd
ren SuperPro.b#9 SuperPro9.brd
ren SuperPro.s#1 SuperPro1.sch
ren SuperPro.s#2 SuperPro2.sch
ren SuperPro.s#3 SuperPro3.sch
ren SuperPro.s#4 SuperPro4.sch
ren SuperPro.s#5 SuperPro5.sch
ren SuperPro.s#6 SuperPro6.sch
ren SuperPro.s#7 SuperPro7.sch
ren SuperPro.s#8 SuperPro8.sch
ren SuperPro.s#9 SuperPro9.sch
