// This file is generated by topld.pl 
// Please don't edit it. 
// Input Pins 
// Output Pins 
// Internal nodes 
// Code nodes 
// Equations 
// c1: c_us 
// c2: c_us 
// c3: c_us 
// e1: sn7474 
always @(b1, a1, d1, c1)
  if (~a1) begin
    e1_m <= 1'b0;
  end else
  if (~d1) begin
    e1_m <= 1'b1;
  end else
  if (~(b1)) begin
    e1_m <= c1;
  end
always @(b1, a1, d1, e1_m)
  if (~a1) begin
    e1 <= 1'b0;
  end else
  if (~d1) begin
    e1 <= 1'b1;
  end else
  if (b1) begin
    e1 <= e1_m;
  end
assign f1 = ~e1;
always @(d2, a1, f2, e2)
  if (~a1) begin
    h2_m <= 1'b0;
  end else
  if (~f2) begin
    h2_m <= 1'b1;
  end else
  if (~(d2)) begin
    h2_m <= e2;
  end
always @(d2, a1, f2, h2_m)
  if (~a1) begin
    h2 <= 1'b0;
  end else
  if (~f2) begin
    h2 <= 1'b1;
  end else
  if (d2) begin
    h2 <= h2_m;
  end
assign j2 = ~h2;
// e2: sn7474 
always @(h1, a1, k1, j1)
  if (~a1) begin
    l1_m <= 1'b0;
  end else
  if (~k1) begin
    l1_m <= 1'b1;
  end else
  if (~(h1)) begin
    l1_m <= j1;
  end
always @(h1, a1, k1, l1_m)
  if (~a1) begin
    l1 <= 1'b0;
  end else
  if (~k1) begin
    l1 <= 1'b1;
  end else
  if (h1) begin
    l1 <= l1_m;
  end
assign m1 = ~l1;
always @(l2, k2, n2, m2)
  if (~k2) begin
    p2_m <= 1'b0;
  end else
  if (~n2) begin
    p2_m <= 1'b1;
  end else
  if (~(l2)) begin
    p2_m <= m2;
  end
always @(l2, k2, n2, p2_m)
  if (~k2) begin
    p2 <= 1'b0;
  end else
  if (~n2) begin
    p2 <= 1'b1;
  end else
  if (l2) begin
    p2 <= p2_m;
  end
assign r2 = ~p2;
// e3: sn7474 
always @(n1, k2, r1, p1)
  if (~k2) begin
    s1_m <= 1'b0;
  end else
  if (~r1) begin
    s1_m <= 1'b1;
  end else
  if (~(n1)) begin
    s1_m <= p1;
  end
always @(n1, k2, r1, s1_m)
  if (~k2) begin
    s1 <= 1'b0;
  end else
  if (~r1) begin
    s1 <= 1'b1;
  end else
  if (n1) begin
    s1 <= s1_m;
  end
assign u1 = ~s1;
always @(s2, k2, u2, t2)
  if (~k2) begin
    v2_m <= 1'b0;
  end else
  if (~u2) begin
    v2_m <= 1'b1;
  end else
  if (~(s2)) begin
    v2_m <= t2;
  end
always @(s2, k2, u2, v2_m)
  if (~k2) begin
    v2 <= 1'b0;
  end else
  if (~u2) begin
    v2 <= 1'b1;
  end else
  if (s2) begin
    v2 <= v2_m;
  end
assign v1 = ~v2;
// Open collector 'wire-or's 
endmodule
