#!/usr/bin/perl

#
# Read a set of .doc files generated by CUPL,
# outputting equivalent Perl code generators.
#

foreach $f (@ARGV) {
  open(INPUT, $f) || die "$f: $!";
  %pad = ();
  while (<INPUT>) {
    last if /^--- --/;
  }
  while (<INPUT>) {
    next unless /^\s+([!]*)\s+(\S+)\s+(\S+)\s+V/;
    $pad{$2} = $3;
  }
  open(INPUT, $f) || die "$f: $!";
  $name = $f; $name =~ s/.doc$//;
  $name =~ s/.*[\\\/]//;
  $name = "dec$name" if $name =~ /^23/;
  $name = "sn$name" if $name =~ /^74/;
  $name =~ y/A-Z/a-z/;
  print "sub $name {\n";
  while (<INPUT>) {
    last if /^====/;
  }
  while (<INPUT>) {
    last if /^====/;
  }
  while (<INPUT>) {
    s/\r//g;
    last if /^====/;
    if (/^(\S+)\s*=>/) {
      $lh = $1;
      $negate = ($lh =~ s/^!//);
$suffix = "";
$suffix = $1 if $lh =~ s/(\..*)//;
      if (!defined $pad{$lh}) {
#       warn "No symbol $lh\n";
        $first = 1;
        undef $lh;
        next;
      }
      $lh = "\$pad\{$pad{$lh}\}";
      $code = "$lh$suffix = ";
      $code .= "!(" if $negate;
      $first = 1;
    } elsif (/^\r*$/) {
      # Wrap up the assignment.
      chop $code; chop $code; # Remove last "\n"
      $code .= ")" if $negate;
      print "  &qcode(\"$code;\\n\") if defined $lh;\n" if defined $lh;
      $code = "";
      undef $lh;
    } else {
      next unless defined $lh;
      s/\s+//g;
      # Replace identifiers with '$pad{n}' where 'n' is the 
      # corresponding pad number.
      s/\b(\d+)\b/'b'$1/;
      foreach $id (keys %pad) {
        s/\b$id\b/\$pad\{$pad{$id}\}/g;
      }
      $code .= "   " unless $first;
      $code .= "$_\\n";
      $first = 0;
    }
  }
  print "}\n\$hidden{\"$name\"} = 0;\n\n"
}
print "1;\n";
